name: Codzienny Tor Scraper

on:
  schedule:
    # 01:00 UTC oraz 13:00 UTC
    - cron: '0 1 * * *'
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Pobierz kod repozytorium
        uses: actions/checkout@v4

      - name: Ustaw środowisko Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Zainstaluj biblioteki
        run: pip install requests

      - name: Uruchom skrypt
        run: python scraper.py

      - name: Commit i Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Dodajemy pliki
          git add latest_*.json history/*.json
          
          # Commitujemy
          git commit -m "Aktualizacja danych JSON: $(date +'%Y-%m-%d %H:%M')" || echo "Brak zmian"
          git push